version: '3.8'

services:
  clock_app:
    build: ./clock_app
    ports:
      - "5001:5001"
    networks:
      - clock_net

  button_app:
    build: ./button_app
    ports:
      - "5002:5002"
    environment:
      - CLOCK_APP_URL=http://clock_app:5001
    networks:
      - clock_net

networks:
  clock_net:
